package helps

import (
	"bytes"
	_ "embed"
	"encoding/json"
	"fmt"
	"net/http"
	"reflect"
	"strconv"

	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

// These are generated by the pinned CLI schema pipeline, not handwritten templates.
//
//go:embed codex_lite_fixtures/0.156.0/image_gen.json
var codexLiteImageNamespace string

//go:embed codex_lite_fixtures/0.156.0/web.json
var codexLiteWebNamespace string

// Keep verified native 0.154 declarations intact when an older client sends them.
//
//go:embed codex_lite_fixtures/0.154.0/image_gen.json
var codexLiteImageNamespace154 string

// Legacy templates identify only the known CPA defect; arbitrary schemas are never replaced.
//
//go:embed codex_lite_fixtures/legacy/image_gen.json
var codexLegacyImageNamespace string

//go:embed codex_lite_fixtures/legacy/web.json
var codexLegacyWebNamespace string

type codexReservedToolSchemaError struct {
	name   string
	legacy bool
}

func (e *codexReservedToolSchemaError) Error() string {
	message := fmt.Sprintf("Codex Responses Lite reserved tool %q conflicts with the verified CLI definitions; use a complete supported CLI declaration instead of a hand-written reserved definition", e.name)
	code := "codex_reserved_tool_schema_conflict"
	if e.legacy {
		message = fmt.Sprintf("Codex Responses Lite reserved tool %q uses an obsolete CPA schema in an existing context; start a new context or rebuild and fully replay it with the corrected definition", e.name)
		code = "codex_reserved_tool_schema_legacy_context"
	}
	raw, _ := json.Marshal(map[string]any{"error": map[string]any{
		"message": message, "type": "invalid_request_error", "param": "tools", "code": code,
	}})
	return string(raw)
}

func (*codexReservedToolSchemaError) StatusCode() int       { return http.StatusBadRequest }
func (*codexReservedToolSchemaError) IsRequestScoped() bool { return true }

func codexToolJSONEqual(left, right string) bool {
	decode := func(raw string) (any, error) {
		decoder := json.NewDecoder(bytes.NewBufferString(raw))
		decoder.UseNumber()
		var value any
		err := decoder.Decode(&value)
		return value, err
	}
	a, errA := decode(left)
	b, errB := decode(right)
	return errA == nil && errB == nil && reflect.DeepEqual(a, b)
}

func codexReservedSchemaFreshContext(body []byte) bool {
	if gjson.GetBytes(body, "previous_response_id").Exists() {
		return false
	}
	for _, item := range gjson.GetBytes(body, "input").Array() {
		typ := item.Get("type").String()
		if typ == "additional_tools" && item.Get("id").Exists() {
			return false
		}
		if typ != "" && typ != "message" && typ != "additional_tools" || item.Get("role").String() == "assistant" {
			return false
		}
	}
	return true
}

// normalizeCodexReservedDeclarations preserves verified definitions and only
// repairs exact legacy templates in fresh contexts. History is never rewritten.
func normalizeCodexReservedDeclarations(body []byte, originalRequests ...[]byte) ([]byte, error) {
	fresh := codexReservedSchemaFreshContext(body)
	for _, original := range originalRequests {
		fresh = fresh && codexReservedSchemaFreshContext(original)
	}
	var conflict error
	var normalize func(gjson.Result, string) ([]byte, bool)
	normalize = func(tools gjson.Result, parent string) ([]byte, bool) {
		if !tools.IsArray() {
			return nil, false
		}
		raw := []byte(tools.Raw)
		changed := false
		for index, tool := range tools.Array() {
			path := strconv.Itoa(index)
			if tool.Get("type").String() == "namespace" {
				if children, replaced := normalize(tool.Get("tools"), tool.Get("name").String()); replaced {
					raw, _ = sjson.SetRawBytes(raw, path+".tools", children)
					changed = true
				}
				continue
			}
			if tool.Get("type").String() != "function" {
				continue
			}
			name := tool.Get("name").String()
			for _, spec := range []struct{ namespace, name, canonical, previous, legacy string }{
				{"image_gen", "imagegen", codexLiteImageNamespace, codexLiteImageNamespace154, codexLegacyImageNamespace},
				{"web", "run", codexLiteWebNamespace, codexLiteWebNamespace, codexLegacyWebNamespace},
			} {
				if !(parent == spec.namespace && name == spec.name || parent == "" && (name == spec.namespace+"."+spec.name || name == spec.namespace+"__"+spec.name)) {
					continue
				}
				canonical, _ := sjson.Set(gjson.Parse(spec.canonical).Get("tools.0").Raw, "name", name)
				previous, _ := sjson.Set(gjson.Parse(spec.previous).Get("tools.0").Raw, "name", name)
				if codexToolJSONEqual(tool.Raw, canonical) || codexToolJSONEqual(tool.Raw, previous) {
					continue
				}
				legacy, _ := sjson.Set(gjson.Parse(spec.legacy).Get("tools.0").Raw, "name", name)
				knownLegacy := codexToolJSONEqual(tool.Raw, legacy)
				if !knownLegacy || !fresh {
					conflict = &codexReservedToolSchemaError{name: spec.namespace + "." + spec.name, legacy: knownLegacy}
					return nil, false
				}
				raw, _ = sjson.SetRawBytes(raw, path, []byte(canonical))
				changed = true
			}
		}
		return raw, changed
	}
	updated := transformCodexToolLists(body, func(list gjson.Result) ([]byte, bool) { return normalize(list, "") })
	if conflict != nil {
		return nil, conflict
	}
	return updated, nil
}
